kind: Deployment
apiVersion: apps/v1
metadata:
  name: task-backend-deployment
  namespace: task-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: task-backend
  template:
    metadata:
      name: task-backend-deployment-pod
      labels:
        app: task-backend
    spec:
      containers:
        - name: task-backend
          image: rohankhanal14/task-backend:cleanup
          ports:
            - containerPort: 5050
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NODE_ENV
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: connection-string
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "200m"
